process.env.NEXT_PUBLIC_SUPABASE_API_KEY = 'somekey'
process.env.NEXT_PUBLIC_SUPABASE_URL = 'https://someurl.com'
process.env.NEXT_PUBLIC_OPENAI_API_KEY = 'somekey'
process.env.NEXT_PUBLIC_TMBD_ACCESS_TOKEN = 'sometoken'
process.env.NODE_ENV = 'test'