import type { Metadata } from 'next'
import './globals.css'
import { carterOne, robotoSlab } from './fonts'
import Image from 'next/image'
import popcorn from '@/public/popcorn.png'
import { MovieProvider } from '@/contexts/MovieContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${carterOne} ${robotoSlab} antialiased bg-base-100 h-screen flex justify-center items-center`}
      >
        <MovieProvider>
          <main className="mx-auto px-8 flex flex-col items-center">
            <Image src={popcorn} alt="" className="mx-auto" />
            <h1 className="text-5xl text-center">PlotlineAI</h1>
            {children}
          </main>
        </MovieProvider>
      </body>
    </html>
  )
}
